# Generated by Django 3.0.6 on 2020-11-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindexpage',
            name='big_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='button_href',
            field=models.CharField(default='jakobendler.eu/404', max_length=255),
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='button_text',
            field=models.CharField(default='Visit Project', max_length=30),
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='github_href',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
