# Generated by Django 3.0.6 on 2020-11-06 14:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailimages', '0022_uploadedimage'),
        ('projects', '0002_auto_20201106_1341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectIndexPage',
            new_name='ProjectPage',
        ),
    ]
