# Generated by Django 3.0.6 on 2020-11-02 16:42

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='about_me_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='get_in_touch_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='headline',
            field=models.CharField(default='Jakob Endler', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subheadline',
            field=models.CharField(default='Subheadline', max_length=255),
        ),
    ]
